CarryMobil/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from core.sitemaps import StaticViewSitemap, SnippetSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'snippet': SnippetSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # path('account/', include("account.urls")),
    path('account/', include("users.urls")),
    path('order/', include("order.urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views
 


urlpatterns = [
    url(r"login/$", views.LoginView.as_view(), name="signin"),
    path('signup/', views.SignUp.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('base.html', views.site_base, name='site_base'),
    path('password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('password/reset_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    
    path('password/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password/reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

apps/core/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    patronymic = models.CharField(max_length=50, blank=True)
    company = models.CharField(max_length=40, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    telephone_number = models.CharField('Номер телефона', max_length=20)

    def __str__(self):
        return self.user.username

    class Meta:
        app_label = "core"


class JobApplication(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    job_type = models.CharField('Вид деятельности', max_length=50)
    passport_series = models.CharField('Серия паспорта', max_length=4)
    passport_number = models.CharField('Номер паспорта', max_length=6)
    registration_address = models.CharField('Адресс прописки', max_length=250)
    driver_licenses_series = models.CharField('Серия водительского удостоверения', max_length=4, blank=True)
    driver_licenses_number = models.CharField('Номер водительского удостоверения', max_length=6, blank=True)
    telephone_number = models.CharField('Номер телефона', max_length=20)

    def __str__(self):
        return self.user.username 
    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    stars = models.IntegerField(null=True, blank=True, default=1)
    likes = models.IntegerField(null=True, blank=True, default=0)
    published_date = models.DateTimeField(default=timezone.now)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text


class Report(models.Model):
    report_text = models.TextField()
    published_date = models.DateTimeField(default=timezone.now, null=True, blank=True)


class Snippet(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(blank=True, null=True)
    body = models.TextField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return f'/{self.slug}/'


class AssistantLibrary(models.Model):
    user_answer = models.CharField('Ответ пользователя', max_length=150,blank=True)
    assistant_text = models.TextField('Текст ассистента',blank=True)
    function_id = models.IntegerField('Функция',null=True, blank=True, default=0)

    def __str__(self):
        return self.user_answer

    class Meta:
        verbose_name = 'Ответ ассистента'
        verbose_name_plural = 'Словарь ассистента'


class Company(models.Model):
    company_name = models.CharField('Имя компании', max_length=128)
    company_inn = models.CharField('ИНН компании', max_length=12)
    business_type = models.CharField('Вид деятельности', max_length=128)
    legal_address = models.CharField('Юридический адрес', max_length=128)
    actual_address = models.CharField('Фактический адрес', max_length=128)
    contact_name = models.CharField('Имя контакта', max_length=128)
    contact_phone = models.CharField('Телефон контакта', max_length=12)
    contact_email = models.EmailField('Эл.почта контакта', max_length=64)
    contact_user = models.OneToOneField(
        User,
        related_name='company',
        on_delete=models.PROTECT
    )
    status = models.BooleanField('Статус компании', default=0)

apps/users/forms.py
from django import forms
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea, NumberInput, PasswordInput
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignupForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        del self.fields["username"]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class SignInForm(AuthenticationForm):
    class Meta:
        username = forms.CharField(widget=TextInput(attrs={'class': 'validate', 'placeholder': 'Email'}))
        password = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'Password'}))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Придумайте свой логин',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ваша электронная почта',
                'required': True
            }),
            'password1': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Придумайте пароль',
            }),
            'password2': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Повторите пароль',
            }),
        }

apps/users/views.py
from django.forms.models import ModelForm
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import auth
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
from django.db import transaction
from datetime import timedelta, datetime
from openpyxl import Workbook
from django.contrib import messages
from . import forms
from django.views.generic import FormView
from django.contrib.auth.views import logout_then_login
import account.forms
import account.views



class LoginView(account.views.LoginView):
    form_class = account.forms.LoginEmailForm

class SignupView(ModelForm):
    form_class =  forms.SignupForm



def sign_in(request):
    form = forms.SignInForm
    return render(request, 'account/login.html', {'form': form})


class SignUp(generic.CreateView):
    form_class = forms.SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'account/signup.html'

    def generate_username(self, form):
        username = form.cleaned_data["email"]
        return username


def log_out(request):
    logout_then_login(request)
    return redirect(reverse("core:home"))

def site_base(request):
    return render(request, 'base.html', {})

def password_reset(request):
    return render(request, 'password_reset.html', {})

templates/user/job_application.html
{% extends "main/index.html" %}
{% block title %}Заявление на работу - Cmobil{% endblock %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'styles/profile.css' %}">
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="white_area">
                <div class="application_form">
                    <form method="post">
                        {% csrf_token %}
                        <h1>Приём на работу</h1>
                        <p>Мы гарантируем конфиденциальность и неразглашения 
                            Ваших персональных данных, полученных в ходе заполнения анкеты</p>
                        <section>
                                <label for=""><h2>Должность</h2></label>
                                <select name="job_name" id="job_type_select" onchange="$('#id_job_type').val($('#job_type_select :selected').text());">
                                    <option value="Диспетчер" selected disabled hidden>Выберите</option>
                                    <option value="Диспетчер">Диспетчер</option>
                                    <option value="Водитель">Водитель</option>
                                    <option value="Грузчик">Грузчик</option>
                                </select>
                                <span hidden>{{ application_form.job_type }}</span>
                        </section>
                        <section>
                            <h2>Личные данные</h2>
                            <section class="user_dop_info">
                                <!-- {{ application_form.user }} -->
                            </section>
                            <section class="user_dop_info">
                                <label for="">Имя</label> 
                                <input type="text" name="" value="{{ user.first_name }}" id="">
                            </section>
                            <section class="user_dop_info">
                                <label for="">Отчество</label>
                                <input type="text" name="" value="{{ user.profile.patronymic }}" id="">
                            </section>
                            <section class="user_dop_info">
                                <label for="">Фамилия</label>
                                <input type="text" name="" value="{{ user.last_name }}" id="">
                            </section>
                            <section class="user_dop_info">
                                <label for="">День рождения</label> 
                                <input type="datetime-local" name="" value="{{ user.profile.birth_date }}" id="">
                            </section>
                            <section class="user_dop_info">
                                <label for="">Номер телефона</label>
                                <input type="tel" name="" value="{{ user.profile.telephone_number }}" id="">
                            </section>
                            <section class="user_dop_info">
                                <label for="">Серия паспорта {{ application_form.passport_series }}</label> 
                            </section>
                            <section class="user_dop_info">
                                <label for="">Номер паспорта {{ application_form.passport_number }}</label> 
                            </section>
                            <section class="user_dop_info">
                                <label for="">Адрес прописки {{ application_form.registration_address }}</label> 
                            </section>
                            <section class="user_dop_info">
                                <label for="">Серия водительского удостоверения {{ application_form.driver_licenses_series }}</label>  
                            </section>
                            <section class="user_dop_info">
                                <label for="">Номер водительского удостоверения{{ application_form.driver_licenses_number }}</label>  
                            </section>
                            <section class="user_dop_info">
                                <label for="">Номер телефона {{ application_form.telephone_number }}</label>  
                            </section>
                        </section>
                        {% if messages %}
                        <div class="warning">
                            <div class="warning_text">
                                {% for message in messages %}
                                    <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                                {% endfor %}
                            </div>
                            <div class="warning_action">
                                <input type="button" class="standart_button warning_apply" value="Ок">
                            </div>
                        </div>
                    {% endif %}
                        <input type="submit" value="Отправить">
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <p>Вы не авторизированы</p>
    {% endif %}
{% endblock %}

templates/user/profile.html
{% extends "main/index.html" %}
{% block title %}Профиль{% endblock %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'styles/profile.css' %}">
{% endblock %}
{% block content %}
    {% if request.user.is_authenticated and not user.is_superuser or request.user.is_superuser %}
        <div class="profil_area">
            <div class="container">
                <div class="profile_content">
                    <div class="user_content">
                        <div class="flex">
                            <div class="user_image">
                                <div class="user_image_content">
                                    <img src="https://eu.ui-avatars.com/api/?name=
                                        {% if user.first_name and user.last_name %}
                                        {{ user.first_name}}+{{ user.last_name }}
                                        {% else %}
                                        {{ user.username }}
                                        {% endif %}
                                        &background=41A4FF&color=F0FFF0" style="border-radius: 100%" alt="">                                    <img src="{{ user.profile.avatar.url }}">
                                    {{ user.profile.avatar }}
                                    {% if user.id == request.user.id %}
                                    <a href="{% url 'update_profile' %}"><input type="button" value="Редактировать"></a>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="user_personal_info">
                                <div class="user_info">
                                    <label>{{ user.username }}
                                        {% if user.is_superuser %}
                                            <label>(Администратор)</label>
                                        {% else %}
                                        {% if user.is_staff %}
                                            <label>(Сотрудник)</label>
                                        {% else %}
                                            <label>(Пользователь)</label>
                                        {% endif %}
                                        {% endif %}
                                    </label>
                                        <section class="user_dop_info">
                                            <label for="">Фамилия: {{ user.last_name }}</label><span></span>
                                        </section>
                                    <section class="user_dop_info">
                                        <label for="">Имя: {{ user.first_name }}</label><span></span>
                                    </section>
                                    <section class="user_dop_info">
                                        <label for="">Отчество: {{ user.profile.patronymic }}</label><span></span>
                                    </section>
                                    <section class="user_dop_info">
                                        <label for="">Эл. почта: {{ user.email }}</label><span></span><br>
                                    </section>
                                    {% if not user.profile.birth_date == None %}
                                    <section class="user_dop_info">
                                        <label for="">День рождения: {{ user.profile.birth_date }}</label><span></span><br>
                                    </section>
                                    {% endif %}
                                    <section class="user_dop_info">
                                        <label for="">Номер телефона: {{ user.profile.telephone_number }}</label><span></span><br>
                                    </section>
                                    {% if user.is_staff %}
                                    <section class="user_dop_info">
                                        <label id="profile_dop_info">Доп. информация ...</label>
                                    </section>
                                    <div class="profile_dop closed" id="profile_dop">
                                        <section class="user_dop_info">
                                            <label for="">Компания: {{ user.profile.company }}</label><span></span>
                                        </section>
                                        <section class="user_dop_info">
                                            <label for="">Должность: {{ user.groups.all.0 }}</label><span></span>
                                            </section>
                                            {% if its_driver %}
                                                <section class="user_dop_info">
                                                    <label for="">Рейтинг водителя: {{ driver_lvl }}({{ driver.driver_rating }})</label><span></span><br>
                                                </section>
                                                <section class="user_dop_info">
                                                    <label for="">Авто:</label>
                                                    {% for car in cars %}
                                                        <a href="{% url 'driver_cars' pk=driver.id %}">{{ car.registration_number }}</a>
                                                    {% endfor %}
                                                </section>
                                                <section class="user_dop_info">
                                                    <label for="">Выполненые заказы: {{ driver.complited_orders }}</label><span></span><br>
                                                </section>
                                                <section class="user_dop_info">
                                                    <label for="">Отмененные заказы: {{ driver.canceled_orders }}</label><span></span><br>
                                                </section>
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="transition_block">
                        <div class="flex_al">
                            <section class="transiton_param">
                                <a href="{% url 'order_table' %}" class="transiton_param-input">Мои заказы</a>
                            </section>
                        </div>
                    </div>
                    <div class="post_add_block">
                        <div>
                            <table id="user_orders_table">
                                <tr id="user_orders_table_title">
                                    <th class="order_start_time">
                                        Дата исполнения
                                    </th>
                                    <th class="">
                                        Маршрут
                                    </th>
                                    <th class="order_loaders">
                                        Грузчики<br>( чел/час )
                                    </th>
                                    <th class="order_cargo_type">
                                        Вид груза
                                    </th>
                                    <th class="">
                                        Сумма
                                    </th>
                                    <th class="user_orders_table">
                                        Статус
                                    </th>
                                </tr>
                            {% for order in orders %}
                                    <tr data-href="{% url 'order_detail' pk=order.pk %}" class="orders_tr">
                                        <td class="order_start_time">
                                            {% if not order.start_time == None %}
                                            <a href="{% url 'order_detail' pk=order.pk %}">{{ order.start_time }}</a>
                                            <a class="order_start_time" href="{% url 'order_detail' pk=order.pk %}" hidden>{{ order.start_time | date:'c' }}</a>
                                            {% else %}
                                                <a href="{% url 'order_detail' pk=order.pk %}">Не назначена</a>
                                            {% endif %}
                                        </td>
                                        <td class="full_roads">
                                            <a href="{% url 'order_detail' pk=order.pk %}">{{ order.full_road | truncatechars_html:35 }}</a>
                                        </td>
                                        <td class="order_loaders">
                                            {% if not order.loader_count == None %}
                                                <a href="{% url 'order_detail' pk=order.pk %}">{{ order.loader_count }}, {{ order.loader_time_count }}</a>
                                            {% else %}
                                                <a href="{% url 'order_detail' pk=order.pk %}">Не нужны</a>
                                            {% endif %}
                                        </td>
                                        <td class="order_cargo_type">
                                            <a href="{% url 'order_detail' pk=order.pk %}">{{ order.cargo_type }}</a>
                                        </td>
                                        <td class="order_price">
                                            <a href="{% url 'order_detail' pk=order.pk %}">{{ order.order_price }}</a>
                                        </td>
                                        <td class="order_status">
                                            {% if not order.status == None %}
                                                {% if order.status == 0 %}
                                                    <a href="{% url 'order_detail' pk=order.pk %}">Ожидается</a>
                                                {% endif %}
                                                {% if order.status == 1 %}
                                                    <a href="{% url 'order_detail' pk=order.pk %}">Выполнено</a>
                                                {% endif %}
                                                {% if order.status == -1 %}
                                                    <a href="{% url 'order_det  ail' pk=order.pk %}">Отменено</a>
                                                {% endif %}
                                            {% endif %}
                                        </td>
                                    </tr>
                            {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if messages %}
                        <div class="warning">
                            <div class="warning_text">
                                {% for message in messages %}
                                    <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                                {% endfor %}
                            </div>
                            <div class="warning_action">
                                <input type="button" class="standart_button warning_apply" value="Ок">
                            </div>
                        </div>
        {% endif %}
    {% else %}
        {% if not user.is_authenticated %}
        <p>Вы не авторизированы</p>
        {% else %}
        <p>У вас недостаточно прав</p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/user/profile_edit.html
{% extends "main/index.html" %}
{% block title %}Редактирование профиля{% endblock %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'styles/profile.css' %}">
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="profil_area">
            <div class="container">
                <div class="profile_content">
                    <div class="user_content">
                        <form method="post">
                            <div class="flex">
                                <div class="user_image">
                                    <div class="user_image_content">
                                        <img src="https://eu.ui-avatars.com/api/?name=
                                            {% if request.user.first_name %}
                                            {{ request.user.first_name}}+{{ request.user.last_name}}
                                            {% else %}
                                            {{ request.user.username }}
                                            {% endif %}
                                            &background=41A4FF&color=F0FFF0" style="border-radius: 100%" alt="">
                                        <a href=""><input type="submit" value="Сохранить"></a>
                                    </div>
                                </div>
                                <div class="user_personal_info">
                                    <div class="user_info">
                                        <div class="user_dop_info">
                                            <label for="">Имя: {{ user_form.first_name }}</label><span></span>
                                        </div>
                                        <div class="user_dop_info">
                                            <label for="">Отчество: {{ profile_form.patronymic }}</label><span></span>
                                        </div>
                                        <div class="user_dop_info">
                                            <label for="">Фамилия: {{ user_form.last_name }}</label><span></span>
                                        </div>
                                        <div class="user_dop_info">
                                            <label for="">Город: {{ profile_form.location }}</label><span></span>
                                        </div>
                                        <div class="user_dop_info">
                                            <label for="">Email: {{ user_form.email }}</label><span></span>
                                        </div>
                                        <div class="user_dop_info">
                                            <label for="">Компания: {{ profile_form.company }}</label><span></span>
                                        </div>
                                        <div class="user_dop_info">
                                            <label for="">День рождения: {{ profile_form.birth_date }}</label><span></span>
                                        </div>
                                        <div class="user_dop_info">
                                            <label for="">Номер телефона: {{ profile_form.telephone_number }}</label><span></span><br>
                                        </div>
                                            {% csrf_token %}
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
    <p>Вы не авторизированы</p>
{% endif %}
{% endblock %}